# Generated by Django 5.0.3 on 2024-04-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FactNewCustomerRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inner_group",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("subgroup1", models.CharField(blank=True, max_length=255, null=True)),
                ("subgroup", models.CharField(blank=True, max_length=255, null=True)),
                ("the_group", models.CharField(blank=True, max_length=4000, null=True)),
                ("type_group", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("date_key", models.CharField(blank=True, max_length=255, null=True)),
                ("budget", models.FloatField(blank=True, null=True)),
                ("type", models.CharField(max_length=3)),
                ("date", models.CharField(max_length=24)),
                ("currency", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="FactTopCDN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_key", models.CharField(max_length=6)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("kurs", models.CharField(max_length=3)),
                (
                    "inner_group",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
                ("subgroup", models.CharField(blank=True, max_length=255, null=True)),
                ("subgroup1", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("partner", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FactTopTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_key", models.CharField(max_length=6)),
                ("customer", models.CharField(blank=True, max_length=255, null=True)),
                ("bandwidth", models.FloatField(blank=True, null=True)),
                ("subgroup", models.CharField(blank=True, max_length=255, null=True)),
                ("subgroup1", models.CharField(blank=True, max_length=255, null=True)),
                ("the_group", models.CharField(blank=True, max_length=4000, null=True)),
                (
                    "inner_group",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
                ("inex", models.CharField(blank=True, max_length=255, null=True)),
                ("currency", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(max_length=3)),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FactTrafficCDN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dim_month", models.FloatField(blank=True, null=True)),
                ("customer_name", models.TextField(blank=True, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("usage_value", models.FloatField(blank=True, null=True)),
                ("usage_unit", models.TextField(blank=True, null=True)),
                ("partner", models.CharField(blank=True, max_length=20, null=True)),
                ("type", models.CharField(max_length=3)),
            ],
        ),
    ]
