# Generated by Django 5.0.3 on 2024-04-07 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
